/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hproject;
import javax.swing.*;
/**
 *
 * @author GuHeHe
 */
public class MainMenuP extends javax.swing.JDialog {

    /**
     * Creates new form MainMenuP
     */
    private static String staffid;
    String sinfo[]=new String[1];
    public MainMenuP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnubrandentry = new javax.swing.JMenuItem();
        mnuitementry = new javax.swing.JMenuItem();
        mnusupplierentry = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnupurchase = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnusuppliersearch = new javax.swing.JMenuItem();
        mnuitemsearch = new javax.swing.JMenuItem();
        mnubrandsearch = new javax.swing.JMenuItem();
        mnupurchasesearch = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnusupplierupdate = new javax.swing.JMenuItem();
        mnubrandupdate = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff");
        setLocation(new java.awt.Point(600, 250));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME !!!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 90, 220, 60);

        jMenu2.setText("Entry");

        mnubrandentry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mnubrandentry.setMnemonic('b');
        mnubrandentry.setText("Brand Entry");
        mnubrandentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubrandentryActionPerformed(evt);
            }
        });
        jMenu2.add(mnubrandentry);

        mnuitementry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mnuitementry.setMnemonic('i');
        mnuitementry.setText("Item Entry");
        mnuitementry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitementryActionPerformed(evt);
            }
        });
        jMenu2.add(mnuitementry);

        mnusupplierentry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnusupplierentry.setMnemonic('s');
        mnusupplierentry.setText("Supplier Entry");
        mnusupplierentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusupplierentryActionPerformed(evt);
            }
        });
        jMenu2.add(mnusupplierentry);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Process");

        mnupurchase.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnupurchase.setMnemonic('p');
        mnupurchase.setText("Purchase");
        mnupurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnupurchaseActionPerformed(evt);
            }
        });
        jMenu3.add(mnupurchase);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Searching");

        mnusuppliersearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnusuppliersearch.setMnemonic('s');
        mnusuppliersearch.setText("Supplier Search");
        mnusuppliersearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusuppliersearchActionPerformed(evt);
            }
        });
        jMenu5.add(mnusuppliersearch);

        mnuitemsearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mnuitemsearch.setText("Item Search");
        mnuitemsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemsearchActionPerformed(evt);
            }
        });
        jMenu5.add(mnuitemsearch);

        mnubrandsearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnubrandsearch.setText("Brand Search");
        mnubrandsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubrandsearchActionPerformed(evt);
            }
        });
        jMenu5.add(mnubrandsearch);

        mnupurchasesearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnupurchasesearch.setText("Purchase Search");
        mnupurchasesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnupurchasesearchActionPerformed(evt);
            }
        });
        jMenu5.add(mnupurchasesearch);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Update");

        mnusupplierupdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnusupplierupdate.setMnemonic('s');
        mnusupplierupdate.setText("Supplier Update");
        mnusupplierupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusupplierupdateActionPerformed(evt);
            }
        });
        jMenu6.add(mnusupplierupdate);

        mnubrandupdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnubrandupdate.setMnemonic('b');
        mnubrandupdate.setText("Brand Update");
        mnubrandupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubrandupdateActionPerformed(evt);
            }
        });
        jMenu6.add(mnubrandupdate);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("User Setting");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Change User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Exit");

        mnuexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuexit.setMnemonic('e');
        mnuexit.setText("Log Out");
        mnuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuexitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuexit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login l=new Login(null,true);
        l.show();
    }//GEN-LAST:event_mnuexitActionPerformed

    private void mnubrandentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubrandentryActionPerformed
        // TODO add your handling code here:
        BrandEntry be = new BrandEntry(null,true);
        be.show();
    }//GEN-LAST:event_mnubrandentryActionPerformed

    private void mnuitementryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitementryActionPerformed
        // TODO add your handling code here:
        ItemEntry ie = new ItemEntry(null,true);
        ie.show();
    }//GEN-LAST:event_mnuitementryActionPerformed

    private void mnusupplierentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusupplierentryActionPerformed
        // TODO add your handling code here:
        SupplierEntry se = new SupplierEntry(null,true);
        se.show();
    }//GEN-LAST:event_mnusupplierentryActionPerformed

    private void mnupurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnupurchaseActionPerformed
        // TODO add your handling code here:
        sinfo[0]=this.staffid;
        Purchase.main(sinfo);
    }//GEN-LAST:event_mnupurchaseActionPerformed

    private void mnusuppliersearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusuppliersearchActionPerformed
        // TODO add your handling code here:
        SupplierSearch ss = new SupplierSearch(null,true);
        ss.show();
    }//GEN-LAST:event_mnusuppliersearchActionPerformed

    private void mnuitemsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemsearchActionPerformed
        // TODO add your handling code here:
        ItemSearch is = new ItemSearch(null, true);
        is.show();
    }//GEN-LAST:event_mnuitemsearchActionPerformed

    private void mnubrandsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubrandsearchActionPerformed
        // TODO add your handling code here:
        BrandSearch bs = new BrandSearch(null,true);
        bs.show();
    }//GEN-LAST:event_mnubrandsearchActionPerformed

    private void mnupurchasesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnupurchasesearchActionPerformed
        // TODO add your handling code here:
        PurchaseSearch ps = new PurchaseSearch(null,true);
        ps.show();
    }//GEN-LAST:event_mnupurchasesearchActionPerformed

    private void mnusupplierupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusupplierupdateActionPerformed
        // TODO add your handling code here:
        SupplierEdit se = new SupplierEdit(null,true);
        se.show();
    }//GEN-LAST:event_mnusupplierupdateActionPerformed

    private void mnubrandupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubrandupdateActionPerformed
        // TODO add your handling code here:
        BrandEdit bu = new BrandEdit(null,true);
        bu.show();
    }//GEN-LAST:event_mnubrandupdateActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        sinfo[0]=this.staffid;
        ChangeUser.main(sinfo);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        staffid=args[0];
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenuP dialog = new MainMenuP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnubrandentry;
    private javax.swing.JMenuItem mnubrandsearch;
    private javax.swing.JMenuItem mnubrandupdate;
    private javax.swing.JMenuItem mnuexit;
    private javax.swing.JMenuItem mnuitementry;
    private javax.swing.JMenuItem mnuitemsearch;
    private javax.swing.JMenuItem mnupurchase;
    private javax.swing.JMenuItem mnupurchasesearch;
    private javax.swing.JMenuItem mnusupplierentry;
    private javax.swing.JMenuItem mnusuppliersearch;
    private javax.swing.JMenuItem mnusupplierupdate;
    // End of variables declaration//GEN-END:variables
}
