/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hproject;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author GuHeHe
 */
public class PromoSearch extends javax.swing.JDialog {

    /**
     * Creates new form PromoSearch
     */
    mySQLQueries msql = new mySQLQueries();
    DefaultTableModel dtm = new DefaultTableModel();
    Statement ste = null ;
    Connection con = null;
    public PromoSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try
        {
            con = DBConnection.GetMySQLConnection();
        }
        catch(ClassNotFoundException cnfe)
        {
            System.out.println(cnfe);
        }
        catch(SQLException sqle)
        {
            System.out.println(sqle);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        createtable();
        fillprotypeID();
        fillItem("select * from promotion");
    }

    public void fillprotypeID()
    {
        String str[]=msql.getIDForChoice("promotiontype");
        cbotypename.addItem("-Selected-");
        for(int i=0 ; i<str.length ; i++)
        cbotypename.addItem(str[i].toString());
    }
    public void createtable()
    {
        dtm.addColumn("Promotion ID");
        dtm.addColumn("Promotion Type Name");
        dtm.addColumn("Promotion Name");
        dtm.addColumn("Start Date");
        dtm.addColumn("End Date");
        dtm.addColumn("Registration Date");
        tblitem.setModel(dtm);
        setColumnWidth(0,40);
        setColumnWidth(1,100);
        setColumnWidth(2,100);
        setColumnWidth(3,30);
        setColumnWidth(4,30);
        setColumnWidth(5,30);
    }
    public void setColumnWidth(int index , int width)
    {
        DefaultTableColumnModel tcm = (DefaultTableColumnModel)tblitem.getColumnModel();
        TableColumn tc = tcm.getColumn(index);
        tc.setPreferredWidth(width);
    }
    public void openpromotype()
    {
        String str;
        
        if(cbotypename.getSelectedIndex()!=0)
        {
            if(cbotypename.getSelectedItem().toString().equals("One Item Discount"))
            {
                str= "select * from promotion where ptid= 'PT-0000001';";
                fillItem(str);
            }
            else if(cbotypename.getSelectedItem().toString().equals("Gift Discount"))
            {
                str= "select * from promotion where ptid= 'PT-0000002';";
                fillItem(str);
            }
            else if(cbotypename.getSelectedItem().toString().equals("Many Item in One Discount"))
            {
                str= "select * from promotion where ptid= 'PT-0000003';";
                fillItem(str);
            }
        }
    }
    public void fillItem(String sql)
    {
        String strdataitem[]= new String[6];
        try
        {
            Statement ste = con.createStatement();
            while(dtm.getRowCount()>0)
               dtm.removeRow(0);
            ResultSet rs = ste.executeQuery(sql);
            while(rs.next())
            {
                strdataitem[0]=rs.getString(1);//proid
              //  strquery=msql.getMerchandise(rs.getString(2));//merid
                strdataitem[1]=rs.getString(2);//ptid
                strdataitem[1]=msql.getprotypeName(strdataitem[1]);
            //    System.out.println(rs.getString(3));
                strdataitem[2]=rs.getString(5);//name
                strdataitem[3]=rs.getString(3);//sd
                strdataitem[4]=rs.getString(4);//ed
                strdataitem[5]=rs.getString(6);//rd
                dtm.addRow(strdataitem);
            }
            tblitem.setModel(dtm);
        }
        catch(SQLException sqle)
        {
            System.out.println(sqle);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbotypename = new javax.swing.JComboBox();
        btnshowall = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblitem = new javax.swing.JTable();
        btnclose = new javax.swing.JButton();
        btnitemdetail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Promotion Search");
        setLocation(new java.awt.Point(600, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Promotion Search :"));
        jPanel1.setLayout(null);

        cbotypename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotypenameActionPerformed(evt);
            }
        });
        jPanel1.add(cbotypename);
        cbotypename.setBounds(190, 60, 170, 26);

        btnshowall.setMnemonic('a');
        btnshowall.setText("ShowAll");
        btnshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowallActionPerformed(evt);
            }
        });
        jPanel1.add(btnshowall);
        btnshowall.setBounds(440, 60, 170, 29);

        tblitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name | Brand | Type", "Price", "Quantity", "Remark"
            }
        ));
        jScrollPane1.setViewportView(tblitem);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 610, 160);

        btnclose.setMnemonic('l');
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose);
        btnclose.setBounds(430, 300, 180, 29);

        btnitemdetail.setMnemonic('i');
        btnitemdetail.setText("Item Detail");
        btnitemdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitemdetailActionPerformed(evt);
            }
        });
        jPanel1.add(btnitemdetail);
        btnitemdetail.setBounds(10, 300, 180, 29);

        jLabel1.setText("Promotion Type");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 30, 120, 20);

        jLabel2.setText("Promotion ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 120, 20);

        txtpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpidKeyPressed(evt);
            }
        });
        jPanel1.add(txtpid);
        txtpid.setBounds(20, 60, 150, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowallActionPerformed
        // TODO add your handling code here:

        fillItem("select * from promotion");
    }//GEN-LAST:event_btnshowallActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        if((JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?","Confirm exiting.",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE))==JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnitemdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitemdetailActionPerformed
        // TODO add your handling code here:
        int r = tblitem.getSelectedRow();
        String s[]=new String[2];
        s[0]=tblitem.getValueAt(r, 0).toString();//item id
        s[1]=tblitem.getValueAt(r, 5).toString();//date
        System.out.println("haha");
        PromoDetail.main(s);
    }//GEN-LAST:event_btnitemdetailActionPerformed

    private void cbotypenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotypenameActionPerformed
        // TODO add your handling code here:
        openpromotype();
    }//GEN-LAST:event_cbotypenameActionPerformed

    private void txtpidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpidKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtpidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PromoSearch dialog = new PromoSearch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnitemdetail;
    private javax.swing.JButton btnshowall;
    private javax.swing.JComboBox cbotypename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblitem;
    private javax.swing.JTextField txtpid;
    // End of variables declaration//GEN-END:variables
}
