/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hproject;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import hproject.mySQLQueries;
import hproject.Checking;
import hproject.MyDate;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author GuHeHe
 */
public class Purchase extends javax.swing.JDialog {

    /**
     * Creates new form Purchase
     */
    mySQLQueries msql = new mySQLQueries();
    MyDate md = new MyDate();
    String strdataitem[]=new String[9];
    String strquery[]=new String[5];
    Vector vid = new Vector();
    Vector vamount = new Vector();
    String str[],stri[];
    int removerow = 0;
    int rowcount = 0;
    int totalamount = 0;
    int dataqty = 0;
    int tempqty = 0;
    DefaultTableModel dtm = new DefaultTableModel();
    boolean b = false ;
    private static String staffid;
    public Purchase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AutoID();
        createtable();
        tblpurchase.setSelectionMode(0);
        lbldate.setText(md.getdate());
    }
    
    public void createtable()
    {
        dtm.addColumn("No");
        dtm.addColumn("Item ID");
        dtm.addColumn("Item Detail");
        dtm.addColumn("Price");
        dtm.addColumn("Quantity");
        dtm.addColumn("Amount");
        tblpurchase.setModel(dtm);
        setColumnWidth(0,5);
        setColumnWidth(1,60);
        setColumnWidth(2,250);
        setColumnWidth(3,40);
        setColumnWidth(4,20);
        setColumnWidth(5,50);
    }
    
    public void setColumnWidth(int index , int width)
    {
        DefaultTableColumnModel tcm = (DefaultTableColumnModel)tblpurchase.getColumnModel();
        TableColumn tc = tcm.getColumn(index);
        tc.setPreferredWidth(width);
    }
    
    public void AutoID()
    {
        lblpurid.setText((String.valueOf(msql.getAutoid("purchaseid", "purchase", "P-"))));
    }
    
    public int totalsp(int sp)
    {
        int tenper;
        tenper=sp/10;
        sp=sp+tenper;
        //System.out.println("10 per is : "+sp);
        return sp;
    }

    public String changefixpri(int cfp)
    {
        int cvi = 0;
        String str = null;
        if(cfp%100!=0)
        {
            cvi=(int) (cfp/100);
            cvi=cvi*100;
            cvi=cvi+100;
        }
        else
        {
            cvi=cfp;
        }
        str=Integer.toString(cvi);
        return str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void showSupplier()
    {
        String result1[]=new String[4];
        result1 = msql.getSupplierData(txtsupid.getText());
        txtsupname.setText(result1[0]);
        lbladd.setText(result1[1]);
        lblph.setText(result1[2]);
        lblemail.setText(result1[3]);

    }
    
    public void showSupplier01()
    {
        String result1[]=new String[4];
        result1 = msql.getSupplierData01(txtsupname.getText());
        txtsupid.setText(result1[0]);
        lbladd.setText(result1[2]);
        lblph.setText(result1[3]);
        lblemail.setText(result1[4]);

    }
    
    public void clearItem()
    {
        lblitemname.setText("");
        txtprice.setText("");
        txtquantity.setText("");
        txtitemid.setText("");
        lblemail.setText("");
        tempqty=0;
    }
    
    public void clear()
    {
        txtsupname.setText("");
        lbladd.setText("");
        lblph.setText("");
        lblitemname.setText("");
        lbltotalamount.setText("");
        txtsupid.setText("");
        txtitemid.setText("");
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
        tblpurchase.setModel(dtm);
        vid.removeAllElements();
        vamount.removeAllElements();
    }
    
    public void itemaddmethod()
    {
        //System.out.println("add");
        tempqty+=Integer.parseInt(txtquantity.getText());
        //System.out.println("sum tempqty" +tempqty);
        String sqty=String.valueOf(tempqty);
        //System.out.println(sqty);
        strdataitem[0]=String.valueOf(vid.size()+1);  //for number
        vid.addElement(strdataitem[1]);//itemid
       // strdataitem[2]+="|"+strdataitem[6]+"|"+strdataitem[7]+"|"+strdataitem[8]; // 2= name, 6=brand,  7= type , 8=remark 
        strdataitem[3]=txtprice.getText();  // price
        strdataitem[4]=txtquantity.getText(); //Qty
        if(!sqty.equals("0"))
        {            
            strdataitem[4]=sqty;
        }
        Long amount = Long.parseLong(strdataitem[4])*Long.parseLong(strdataitem[3]);  // $ * Qty
        strdataitem[5]=String.valueOf(amount);  //total
        vamount.addElement(strdataitem[5]);
        dtm.addRow(strdataitem);
        tblpurchase.setModel(dtm);
        dataqty=Integer.parseInt(strdataitem[4]);
       // System.out.println(dataqty);
        txtitemid.requestFocus();      
        rowcount++;     

    }
    public void deleteRow()
    {
        int i = tblpurchase.getSelectedRow();
        vamount.remove(i);
        int no ;
        if(!vid.lastElement().equals(vid.get(i)))
        {
            vid.remove(i);
            no = vid.indexOf(vid.get(i));
            dtm.removeRow(i);
            dtm.setValueAt(no+1, i, 0);

        }
        else
        {
            vid.remove(i);
            dtm.removeRow(i);

        }
        rowcount--;
        tblpurchase.setModel(dtm);
        lbltotalamount.setText(Checking.Sumamount(vamount, 1)+"Kyats");
        totalamount=Checking.Sumamount01(vamount);

    }
    
    public void deleteRow01()
    {
        vamount.remove(removerow);
        int no ;
        //System.out.println(removerow);
        //System.out.println("table coloum"+tblpurchase.getValueAt(removerow, 4));
        tempqty=Integer.parseInt((String)tblpurchase.getValueAt(removerow, 4));
        //System.out.println("temp qty is " + tempqty);
        if(!vid.lastElement().equals(vid.get(removerow)))
        {
            vid.remove(removerow);
            no = vid.indexOf(vid.get(removerow));
            dtm.removeRow(removerow);
            dtm.setValueAt(no+1, removerow, 0);

        }
        else
        {
            vid.remove(removerow);
            dtm.removeRow(removerow);

        }
        rowcount--;
        tblpurchase.setModel(dtm);
        lbltotalamount.setText(Checking.Sumamount(vamount, 1)+"Kyats");
        totalamount=Checking.Sumamount01(vamount);

    }
    public boolean insertpurchase()
    {
        String[]savedata1=new String[5];
        savedata1[0]=lblpurid.getText();
        savedata1[1]=txtsupid.getText();
        savedata1[2]=lbldate.getText();
        savedata1[3]=lblstaffid.getText();
        savedata1[4]=Integer.toString(totalamount);
        return msql.insertData("purchase", savedata1);
    }
    
    public String[] gettabledata()
    {
        String s[] = new String[rowcount];
       // s=tblpurchase.getValueAt(r, 0).toString();
        if(rowcount!=0)
        {
            for(int i=0;i<rowcount;i++)
            {
                s[i]=tblpurchase.getValueAt(i, 1).toString();
               // System.out.println(s.length);
            }
        }
        return s;
    }
    public boolean duplicate(String id)
    {
        boolean b=loop(id, gettabledata());
        return b;
    }
    public boolean loop(String str01, String []str02)
    {
       // boolean b=false;
        for(int i=0;i<rowcount;i++)
        {
           // System.out.println(str01+" is enter username");
           // System.out.println("real username is "+str02[i]);
            if(str01.equals(str02[i]))
            {
               // System.out.println("Answer is true");
                removerow=i;
                //System.out.println(removerow +"DDDDDDDDDDDDDDD");
                return true;
            }
            else
            {
               // System.out.println("Noooooooooooooooooooooooooooooooooooooooo");
            }
        }
        return false; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        txtprice = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        lblitemname = new javax.swing.JLabel();
        txtitemid = new javax.swing.JTextField();
        txtsupname = new javax.swing.JTextField();
        lbladd = new javax.swing.JTextField();
        lblph = new javax.swing.JTextField();
        lblemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpurchase = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        lblpurid = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltotalamount = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblstaffid = new javax.swing.JLabel();
        txtsupid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Purchase");
        setLocation(new java.awt.Point(600, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Supplier ID :");

        jLabel2.setText("Supplier Name:");

        jLabel3.setText("Address :");

        jLabel4.setText("Phone No :");

        jLabel5.setText("Company Name: ");

        jLabel6.setText("Purchase ID :");

        jLabel7.setText("Date :");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Info :"));
        jPanel2.setToolTipText("");

        jLabel8.setText("Item ID :");

        jLabel9.setText("Item Name :");

        jLabel11.setText("Price :");

        jLabel12.setText("Quantity :");

        btnadd.setMnemonic('a');
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setMnemonic('d');
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setMnemonic('u');
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        lblitemname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtitemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtitemidKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblitemname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtitemid))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprice, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtquantity)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnadd)
                        .addGap(78, 78, 78)
                        .addComponent(btndelete)
                        .addGap(94, 94, 94)
                        .addComponent(btnupdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtitemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(lblitemname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btndelete)
                    .addComponent(btnupdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtsupname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsupnameKeyPressed(evt);
            }
        });

        tblpurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpurchase);

        jLabel14.setText("Total Amount :");

        btnsave.setMnemonic('s');
        btnsave.setText("Save");
        btnsave.setBorder(null);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnclose.setMnemonic('c');
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        lblpurid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbldate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbltotalamount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setText("Staff ID :");

        lblstaffid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblstaffid.setText(staffid);

        txtsupid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsupidKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsupname, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(lbladd)
                            .addComponent(lblph)
                            .addComponent(lblemail)
                            .addComponent(txtsupid))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbldate, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(lblpurid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblstaffid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(lbltotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblpurid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)))
                    .addComponent(txtsupid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7)
                                .addComponent(txtsupname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbladd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblstaffid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        if(txtitemid.getText().equals(null))
        {
            JOptionPane.showMessageDialog(null, "You must Enter Item ID!");
            txtitemid.requestFocus();
            if(!Checking.checktxtprice(txtprice.getText()))
            {
                txtprice.requestFocus();
                txtprice.selectAll();
            }
            else if(!Checking.checktxtquantity(txtquantity.getText()))
            {
                txtquantity.requestFocus();
                txtquantity.selectAll();
            }
            else if(!Checking.checkqtyhigh(dataqty,Integer.parseInt(txtquantity.getText())))
            {
                txtquantity.requestFocus();
                txtquantity.selectAll();
            }
        }
        
        else
        {
            boolean tf=duplicate(txtitemid.getText());
            // System.out.println(tf);
            if(tf)
            {
                deleteRow01();
            }
            itemaddmethod();
            lbltotalamount.setText(Checking.Sumamount(vamount,1)+"Kyats");
            totalamount=Checking.Sumamount01(vamount);
            clearItem();
           // txtitemid.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if(tblpurchase.getSelectedRow()<0)
        JOptionPane.showMessageDialog(this, "Please select row to delete.");
        else
        {
            deleteRow();
            clearItem();
           // txtitemid.setSelectedIndex(0);
            lbltotalamount.setText(Checking.Sumamount(vamount, 1)+"Kyats");
            totalamount=Checking.Sumamount01(vamount);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if(tblpurchase.getSelectedRow()<0)
        {
            JOptionPane.showMessageDialog(this, "Please select row to update");
        }
        else if(!Checking.checktxtprice(txtprice.getText()))
        {
            txtprice.requestFocus();
            txtprice.selectAll();
        }
        else if(!Checking.checktxtquantity(txtquantity.getText()))
        {
            txtquantity.requestFocus();
            txtquantity.selectAll();
        }
        else
        {
            deleteRow();
            itemaddmethod();
            lbltotalamount.setText(Checking.Sumamount(vamount,1)+"Kyats");
            totalamount=Checking.Sumamount01(vamount);
            clearItem();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if(Checking.IsNull(txtsupid.getText()))
        {
            JOptionPane.showMessageDialog(null, "You must select a Supplier ID!");
            txtsupid.requestFocus();
        }
        else if(vid.size()==0)
        {

            JOptionPane.showMessageDialog(null, "There is no item for Purchase!");
            txtsupid.requestFocus();
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Are you sure to Save ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
            {
                boolean save,save01 = false, save02 = false;
                int sellingprice = 0;
                int sellprice = 0;
                String []savedata2=new String[4];
                String []savedata3=new String[5];
                String []savedata4=new String[3];
                String itemid = null;
                int vidsize=0;
                save=insertpurchase();
                vidsize=vid.size();
                
                if(save)
                {
                    for(int i=0 ; i<vid.size() ; i++)
                    {
                        savedata2[0]=lblpurid.getText();
                        savedata2[1]=(String)tblpurchase.getValueAt(i, 1);// pur price
                        savedata2[2]=(String)tblpurchase.getValueAt(i, 3); //qty
                        savedata2[3]=(String)tblpurchase.getValueAt(i, 4); //itemid
                        save=msql.insertData("purchasedetail", savedata2);
                        msql.P_updateitemquantity("purchasedetail", savedata2[1], savedata2[2], savedata2[3]);
                    }
                }

                if(save)
                {
                    for(int j=0;j<vidsize;j++)
                    {
                        savedata3[0]=txtsupid.getText();
                        savedata3[1]=lbldate.getText();
                        savedata3[2]=(String)tblpurchase.getValueAt(j, 1);
                        savedata3[3]=(String)tblpurchase.getValueAt(j, 3);
                        savedata3[4]=(String)tblpurchase.getValueAt(j, 4);
                        save01=msql.insertData("purchasedetail01", savedata3);
                        //System.out.println(savedata3[0]+" "+savedata3[1]+" "+savedata3[2]+" "+savedata3[3]+" "+savedata3[4]);
                    }
                }
                if(save)
                {
                    for(int k=0 ; k<vidsize ; k++)
                    {
                       // System.out.println("Coming");
                        savedata4[0]=(String)tblpurchase.getValueAt(k, 3);//pur price
                        //System.out.println("Purchase Price is : "+savedata4[0]);
                        itemid=(String)tblpurchase.getValueAt(k, 1); //itemid
                      //  System.out.println("ID  is : "+itemid);
                        //System.out.println(vidsize);
                        sellingprice=Integer.parseInt(savedata4[0]);
                        savedata4[1]=changefixpri(totalsp(sellingprice));
                        //savedata4[1]=sellprice.toString(); //selling price
                        System.out.println("Selling Price is : "+savedata4[1]);
                       // System.out.println("    "+itemid+"  "+savedata4[0]+"    "+savedata4[1]);
                        
                        save02=msql.updateRecord("itemdetail01", itemid, savedata4);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Records cannot be saved because of some ERROR!");
                    clear();
                }
                

                if(save02)
                {
                    JOptionPane.showMessageDialog(null, "item YESSSSSSSSSSSS");
                    AutoID();
                    clear();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Item NOOOOOOOOOOOO!");
                    clear();
                }
                if(save01)
                {
                    JOptionPane.showMessageDialog(null, "All records are successfully SAVED!");
                    AutoID();
                    clear();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Records cannot be saved because of some ERROR!");
                    clear();
                }
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        if((JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?","Confirm exiting.",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE))==JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void tblpurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpurchaseMouseClicked
        // TODO add your handling code here:
        int r = tblpurchase.getSelectedRow();
        txtitemid.setText(tblpurchase.getValueAt(r, 1).toString());
        lblitemname.setText(tblpurchase.getValueAt(r, 2).toString());
        txtprice.setText(tblpurchase.getValueAt(r, 3).toString());
        txtquantity.setText(tblpurchase.getValueAt(r, 4).toString());
    }//GEN-LAST:event_tblpurchaseMouseClicked

    private void txtitemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemidKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // System.out.println("Right key typed");
            
            strquery = msql.getItemData1(txtitemid.getText());
            strdataitem[1]=strquery[0];//itemid
            strdataitem[2]=strquery[1];//itemname
            strdataitem[3]=msql.getTypeName(strquery[2]);//type name
            lblitemname.setText(strdataitem[2]);
            strdataitem[4]=strquery[3];//sale price
            txtprice.setText(strdataitem[4]);
            txtquantity.setText("1");
            txtquantity.requestFocus();
            //   getRootPane().setDefaultButton(btnupdate);
        }
    }//GEN-LAST:event_txtitemidKeyPressed

    private void txtsupnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupnameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // System.out.println("Right key typed");
            
            showSupplier01();
            txtitemid.requestFocus();
            //   getRootPane().setDefaultButton(btnupdate);
        }
    }//GEN-LAST:event_txtsupnameKeyPressed

    private void txtsupidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupidKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // System.out.println("Right key typed");
            
            showSupplier();
            txtitemid.requestFocus();
            //   getRootPane().setDefaultButton(btnupdate);
        }
    }//GEN-LAST:event_txtsupidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        staffid=args[0];
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Purchase dialog = new Purchase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbladd;
    private javax.swing.JLabel lbldate;
    private javax.swing.JTextField lblemail;
    private javax.swing.JLabel lblitemname;
    private javax.swing.JTextField lblph;
    private javax.swing.JLabel lblpurid;
    private javax.swing.JLabel lblstaffid;
    private javax.swing.JLabel lbltotalamount;
    private javax.swing.JTable tblpurchase;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtsupid;
    private javax.swing.JTextField txtsupname;
    // End of variables declaration//GEN-END:variables
}
