/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hproject;
import hproject.mySQLQueries;
import hproject.DBConnection;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;
/**
 *
 * @author GuHeHe
 */
public class SaleSearch extends javax.swing.JDialog {

    /**
     * Creates new form SaleSearch
     */
    mySQLQueries msql = new mySQLQueries();
    DefaultTableModel dtm = new DefaultTableModel();
    Statement ste = null ;
    Connection con = null;
    String datetime = null;
    public SaleSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try
        {
            con = DBConnection.GetMySQLConnection();
        }
        catch(ClassNotFoundException cnfe)
        {
            System.out.println(cnfe);
        }
        catch(SQLException sqle)
        {
            System.out.println(sqle);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        createtable();
        fillPurData("select * from sale");
    }

    public void createtable()
    {
        dtm.addColumn("Sale ID");
        dtm.addColumn("Date");
      //  dtm.addColumn("Customer Name");
        dtm.addColumn("Staff Name");
        dtm.addColumn("Total Amount");
        tblpurchase2.setModel(dtm);
        setColumnWidth(0,40);
        setColumnWidth(1,50);
    //    setColumnWidth(2,60);
        setColumnWidth(2,300);
        setColumnWidth(3,40);
    }
    public void setColumnWidth(int index , int width)
    {
        DefaultTableColumnModel tcm = (DefaultTableColumnModel)tblpurchase2.getColumnModel();
        TableColumn tc = tcm.getColumn(index);
        tc.setPreferredWidth(width);
    }
    
    public void fillPurData(String sql)
    {
        String strdataitem[]=new String[4];
        String strquery[]=new String[1];
        String dates = null;
        try
        {
            Statement ste = con.createStatement();
            while(dtm.getRowCount()>0)
                dtm.removeRow(0);
           ResultSet rs = ste.executeQuery(sql) ;
           while(rs.next())
           {
               strdataitem[0]=rs.getString(1);//sale id
               strdataitem[1]=rs.getString(3);//sale date
               dates=strdataitem[1];
               strdataitem[1]=dates.substring(0, 10);
              // strquery = msql.getCustomerData(rs.getString(2));//supplierid to supplierdata
            //   strdataitem[2]=strquery[0];//suppliername
               strquery = msql.getstaffdata(rs.getString(2));//itemid to itemdata
               strdataitem[2]=strquery[0];//staff name
               strdataitem[3]=rs.getString(4);//total amount
               /*
               1=saleid
               2=staffid
               3=date
               4=saleid
               5=price
               6=qty
               7=itemid
               */
               dtm.addRow(strdataitem);


           }
           tblpurchase2.setModel(dtm);
        }
        catch(SQLException sqle)
        {
            System.out.println(sqle);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnshowall2 = new javax.swing.JButton();
        btnclose2 = new javax.swing.JButton();
        btnprint2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpurchase2 = new javax.swing.JTable();
        txtmonth = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsaleid = new javax.swing.JTextField();
        btndetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sale Search");
        setLocation(new java.awt.Point(600, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sale Form :"));

        btnshowall2.setMnemonic('a');
        btnshowall2.setText("ShowAll");
        btnshowall2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowall2ActionPerformed(evt);
            }
        });

        btnclose2.setMnemonic('l');
        btnclose2.setText("Close");
        btnclose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose2ActionPerformed(evt);
            }
        });

        btnprint2.setMnemonic('p');
        btnprint2.setText("Print");
        btnprint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprint2ActionPerformed(evt);
            }
        });

        tblpurchase2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sale ID", "Date", "Item Name | Brand | Type", "Price", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(tblpurchase2);

        txtmonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmonthKeyPressed(evt);
            }
        });

        txtyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtyearKeyPressed(evt);
            }
        });

        jLabel1.setText("Month (1-12) :");

        jLabel2.setText("Year :");

        jLabel3.setText("Staff name :");

        txtstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstnameKeyPressed(evt);
            }
        });

        jLabel4.setText("Sale ID :");

        txtsaleid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsaleidKeyPressed(evt);
            }
        });

        btndetail.setText("Detail");
        btndetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btndetail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnprint2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnclose2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtstname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 191, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtsaleid, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnshowall2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsaleid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnshowall2)))
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclose2)
                    .addComponent(btnprint2)
                    .addComponent(btndetail))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowall2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowall2ActionPerformed
        // TODO add your handling code here:
        fillPurData("select * from sale");
    }//GEN-LAST:event_btnshowall2ActionPerformed

    private void btnprint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprint2ActionPerformed
        // TODO add your handling code here:
        try{
            tblpurchase2.print();
        }catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnprint2ActionPerformed

    private void btnclose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose2ActionPerformed
        // TODO add your handling code here:
        if((JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?","Confirm exiting.",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE))==JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_btnclose2ActionPerformed

    private void txtmonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmonthKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(txtmonth.getText().equals("")) {
                JOptionPane.showMessageDialog(this,"Please choose Month");
                txtmonth.requestFocus();
            } else {
                String str = "select * from sale where Month(saledate)='"+txtmonth.getText()+"' ORDER BY Day(saledate) ;";
                fillPurData(str);
            }
        }
    }//GEN-LAST:event_txtmonthKeyPressed

    private void txtyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyearKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(txtyear.getText().equals("")) {
                JOptionPane.showMessageDialog(this,"Please choose Year");
                txtyear.requestFocus();
            } else {
                String str01 = "select * from sale where Year(saledate)="+txtyear.getText();
                fillPurData(str01);
            }
        }
    }//GEN-LAST:event_txtyearKeyPressed

    private void txtstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(txtstname.getText().equals("")) {
                JOptionPane.showMessageDialog(this,"Please Enter staff name");
                txtstname.requestFocus();
            } else {
                String str03 = "SELECT * FROM sale where staffid=(SELECT staffid from staff where name='"+txtstname.getText()+"');";
                fillPurData(str03);
            }
        }
    }//GEN-LAST:event_txtstnameKeyPressed

    private void txtsaleidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsaleidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(txtsaleid.getText().equals("")) {
                JOptionPane.showMessageDialog(this,"Please Enter Sale ID");
                txtyear.requestFocus();
            } else {
                String str04 = "select * from sale where saleid='"+txtsaleid.getText()+"'";
                fillPurData(str04);
            }
        }
    }//GEN-LAST:event_txtsaleidKeyPressed

    private void btndetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetailActionPerformed
        // TODO add your handling code here:
        int r = tblpurchase2.getSelectedRow();
        String s[]=new String[2];
        s[0]=tblpurchase2.getValueAt(r, 0).toString();//sale id
        s[1]=tblpurchase2.getValueAt(r, 1).toString();
        SaleDetail.main(s);
    }//GEN-LAST:event_btndetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaleSearch dialog = new SaleSearch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose2;
    private javax.swing.JButton btndetail;
    private javax.swing.JButton btnprint2;
    private javax.swing.JButton btnshowall2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblpurchase2;
    private javax.swing.JTextField txtmonth;
    private javax.swing.JTextField txtsaleid;
    private javax.swing.JTextField txtstname;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
